"""Version 10

Revision ID: 39792688fbfe
Revises: 7c819a20d3bd
Create Date: 2020-11-26 09:59:53.442717

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '39792688fbfe'
down_revision = '7c819a20d3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_states_old_state_id', table_name='states')
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.create_foreign_key(None, 'states', 'states', ['old_state_id'], ['state_id'])
    op.create_foreign_key(None, 'states', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.create_foreign_key(None, 'states', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'states', 'states', ['old_state_id'], ['state_id'], ondelete='SET NULL')
    op.create_index('ix_states_old_state_id', 'states', ['old_state_id'], unique=False)
    # ### end Alembic commands ###
